/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var sqlite = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,8],$V1=[1,7],$V2=[1,9,21],$V3=[1,17],$V4=[1,20],$V5=[12,17],$V6=[15,17],$V7=[1,38],$V8=[1,45],$V9=[1,35],$Va=[1,36],$Vb=[1,39],$Vc=[1,41],$Vd=[1,42],$Ve=[1,43],$Vf=[1,44],$Vg=[1,49],$Vh=[1,50],$Vi=[12,17,30,32,44],$Vj=[1,51],$Vk=[1,52],$Vl=[12,17,30,32,33,35,44],$Vm=[1,53],$Vn=[12,17,30,32,33,35,36,44],$Vo=[27,29];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"consultas":3,"consulta":4,"crear_tabla":5,"seleccion":6,"registro":7,"actualizacion":8,"IDENTI":9,"CORCHE_APER":10,"valores":11,"CORCHE_CERRA":12,"IN":13,"ENTERO":14,"P_COMA":15,"valor":16,"COMA":17,"ASIGN":18,"expr":19,"PUNTO":20,"TABLE":21,"COLUMNS":22,"columnas_tabla":23,"columna_tabla":24,"TIPO":25,"cadena":26,"COMILLA":27,"caracteres":28,"STRING":29,"SUMA":30,"term":31,"RESTA":32,"MULTI":33,"mod":34,"DIVI":35,"MOD":36,"unario":37,"factor":38,"FLOAT":39,"TRUE":40,"FALSE":41,"CHAR":42,"PAREN_APER":43,"PAREN_CERRA":44,"$accept":0,"$end":1},
terminals_: {2:"error",9:"IDENTI",10:"CORCHE_APER",12:"CORCHE_CERRA",13:"IN",14:"ENTERO",15:"P_COMA",17:"COMA",18:"ASIGN",20:"PUNTO",21:"TABLE",22:"COLUMNS",25:"TIPO",27:"COMILLA",29:"STRING",30:"SUMA",32:"RESTA",33:"MULTI",35:"DIVI",36:"MOD",39:"FLOAT",40:"TRUE",41:"FALSE",42:"CHAR",43:"PAREN_APER",44:"PAREN_CERRA"},
productions_: [0,[3,1],[3,2],[4,1],[4,1],[4,1],[4,1],[8,7],[7,5],[11,1],[11,3],[16,3],[6,4],[5,5],[23,1],[23,3],[24,3],[26,3],[28,1],[28,2],[19,3],[19,3],[19,1],[31,3],[31,3],[31,1],[34,3],[34,1],[37,2],[37,2],[37,1],[38,1],[38,1],[38,1],[38,1],[38,1],[38,1],[38,3]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
}
},
table: [{3:1,4:2,5:3,6:4,7:5,8:6,9:$V0,21:$V1},{1:[3],4:9,5:3,6:4,7:5,8:6,9:$V0,21:$V1},o($V2,[2,1]),o($V2,[2,3]),o($V2,[2,4]),o($V2,[2,5]),o($V2,[2,6]),{9:[1,10]},{10:[1,12],20:[1,11]},o($V2,[2,2]),{22:[1,13]},{9:[1,14]},{9:$V3,11:15,16:16},{9:$V4,23:18,24:19},{15:[1,21]},{12:[1,22],17:[1,23]},o($V5,[2,9]),{18:[1,24]},{15:[1,25],17:[1,26]},o($V6,[2,14]),{18:[1,27]},o($V2,[2,12]),{13:[1,29],15:[1,28]},{9:$V3,16:30},{14:$V7,19:31,26:40,27:$V8,30:$V9,31:32,32:$Va,34:33,37:34,38:37,39:$Vb,40:$Vc,41:$Vd,42:$Ve,43:$Vf},o($V2,[2,13]),{9:$V4,24:46},{25:[1,47]},o($V2,[2,8]),{14:[1,48]},o($V5,[2,10]),o($V5,[2,11],{30:$Vg,32:$Vh}),o($Vi,[2,22],{33:$Vj,35:$Vk}),o($Vl,[2,25],{36:$Vm}),o($Vn,[2,27]),{14:$V7,26:40,27:$V8,38:54,39:$Vb,40:$Vc,41:$Vd,42:$Ve,43:$Vf},{14:$V7,26:40,27:$V8,38:55,39:$Vb,40:$Vc,41:$Vd,42:$Ve,43:$Vf},o($Vn,[2,30]),o($Vn,[2,31]),o($Vn,[2,32]),o($Vn,[2,33]),o($Vn,[2,34]),o($Vn,[2,35]),o($Vn,[2,36]),{14:$V7,19:56,26:40,27:$V8,30:$V9,31:32,32:$Va,34:33,37:34,38:37,39:$Vb,40:$Vc,41:$Vd,42:$Ve,43:$Vf},{28:57,29:[1,58]},o($V6,[2,15]),o($V6,[2,16]),{15:[1,59]},{14:$V7,26:40,27:$V8,30:$V9,31:60,32:$Va,34:33,37:34,38:37,39:$Vb,40:$Vc,41:$Vd,42:$Ve,43:$Vf},{14:$V7,26:40,27:$V8,30:$V9,31:61,32:$Va,34:33,37:34,38:37,39:$Vb,40:$Vc,41:$Vd,42:$Ve,43:$Vf},{14:$V7,26:40,27:$V8,30:$V9,32:$Va,34:62,37:34,38:37,39:$Vb,40:$Vc,41:$Vd,42:$Ve,43:$Vf},{14:$V7,26:40,27:$V8,30:$V9,32:$Va,34:63,37:34,38:37,39:$Vb,40:$Vc,41:$Vd,42:$Ve,43:$Vf},{14:$V7,26:40,27:$V8,30:$V9,32:$Va,37:64,38:37,39:$Vb,40:$Vc,41:$Vd,42:$Ve,43:$Vf},o($Vn,[2,28]),o($Vn,[2,29]),{30:$Vg,32:$Vh,44:[1,65]},{27:[1,66],29:[1,67]},o($Vo,[2,18]),o($V2,[2,7]),o($Vi,[2,20],{33:$Vj,35:$Vk}),o($Vi,[2,21],{33:$Vj,35:$Vk}),o($Vl,[2,23],{36:$Vm}),o($Vl,[2,24],{36:$Vm}),o($Vn,[2,26]),o($Vn,[2,37]),o($Vn,[2,17]),o($Vo,[2,19])],
defaultActions: {},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {"flex":true},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:this.begin('COMENTARIO')
break;
case 1:this.popState()
break;
case 2:/* ignorar comentario */
break;
case 3:this.begin('STRING'); return 27
break;
case 4:this.popState(); return 27
break;
case 5:return 29
break;
case 6:/* ignorar comentarios de una línea */
break;
case 7:return 25
break;
case 8:return 25
break;
case 9:return 22
break;
case 10:return 'DELETE'
break;
case 11:return 41
break;
case 12:return 25
break;
case 13:return 13
break;
case 14:return 25
break;
case 15:return 21
break;
case 16:return 40
break;
case 17:return 25
break;
case 18:return 9
break;
case 19:return 15
break;
case 20:return 17
break;
case 21:return 20
break;
case 22:return 10
break;
case 23:return 12
break;
case 24:return 43
break;
case 25:return 44
break;
case 26:return 30
break;
case 27:return 33
break;
case 28:return 35
break;
case 29:return 'MENOS'
break;
case 30:return 36
break;
case 31:return 18
break;
case 32:return 39
break;
case 33:return 14
break;
case 34:return 42
break;
case 35:/* ignorar espacios en blanco */
break;
case 36:return 'EOF'
break;
case 37:/* manejar error lexico. */
break;
case 38:console.log(yy_.yytext);
break;
}
},
rules: [/^(?:\/\*)/,/^(?:\*\/)/,/^(?:[^])/,/^(?:")/,/^(?:")/,/^(?:[^])/,/^(?:#.*)/,/^(?:boolean)/,/^(?:char)/,/^(?:COLUMNS)/,/^(?:DELETE)/,/^(?:(F|f)alse)/,/^(?:float)/,/^(?:IN)/,/^(?:int)/,/^(?:TABLE)/,/^(?:(T|t)rue)/,/^(?:string)/,/^(?:([a-zA-Z][a-zA-Z0-9_]*))/,/^(?:;)/,/^(?:,)/,/^(?:\.)/,/^(?:\[)/,/^(?:\])/,/^(?:\()/,/^(?:\))/,/^(?:\+)/,/^(?:\*)/,/^(?:\/)/,/^(?:-)/,/^(?:%)/,/^(?:=)/,/^(?:([0-9]+\.[0-9]+))/,/^(?:([0-9]+))/,/^(?:('(\\n|\\t|\\r|\\'|\\\\|\\b|[^'\\\n])'))/,/^(?:\s+)/,/^(?:$)/,/^(?:.)/,/^(?:.)/],
conditions: {"STRING":{"rules":[4,5],"inclusive":false},"COMENTARIO":{"rules":[1,2],"inclusive":false},"INITIAL":{"rules":[0,3,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = sqlite;
exports.Parser = sqlite.Parser;
exports.parse = function () { return sqlite.parse.apply(sqlite, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}